export const FETCH_CUSTOMERS_DATA = 'FETCH_CUSTOMERS_DATA';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDER_DETAILS = 'FETCH_ORDER_DETAILS';
export const FETCH_EMPLOYEES_DATA = 'FETCH_EMPLOYEES_DATA';
export const FETCH_OFFICES_DATA = 'FETCH_OFFICES_DATA';
export const FETCH_PAYMENTS_DATA = 'FETCH_PAYMENTS_DATA';
export const FETCH_PRODUCTS_DATA = 'FETCH_PRODUCTS_DATA';
export const FETCH_PRODUCTS_LINES_DATA = 'FETCH_PRODUCTS_LINES_DATA';
export const FETCH_DAILY_REPORTS = 'FETCH_DAILY_REPORTS';
export const FETCH_REPORT_BY_DATE = 'FETCH_REPORT_BY_DATE';

